name: Flask Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace with your Python version

    - name: Decode SSH Key
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$EC2_SSH_KEY" | base64 --decode > ec2_ssh_key.pem
        chmod 600 ec2_ssh_key.pem



    - name: SSH and Execute Command
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -vvv -i ec2_ssh_key.pem -o "StrictHostKeyChecking=no" "$EC2_USER@$EC2_HOST" 'bash -s' < deploy.sh
