name: Flask Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Set the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Replace with your Python version

    - name: Set up SSH key
      env:
        EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        TEMP_SSH_KEY=$(mktemp)
        echo "$EC2_SSH_KEY" | base64 --decode > "$TEMP_SSH_KEY"
        chmod 600 "$TEMP_SSH_KEY"
        echo "SSH_KEY=$TEMP_SSH_KEY" >> $GITHUB_ENV

    - name: Flask Deploy to AWS EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        SSH_KEY: ${{ env.SSH_KEY }}
      run: |
        ssh -i "$SSH_KEY" -o "StrictHostKeyChecking=no" "$EC2_USER@$EC2_HOST" 'bash -s' < deploy.sh
